// src/lib/CollapsedMenu.svelte
<script lang="ts" >
    import Heading from "./Heading.svelte";
    export let heading:string;
    let collapsed = true;
    const toogleButton = () => {
        collapsed = !collapsed;
    };
</script>
<div class="flex flex-row items-center justify-between w-full p-2">
    <Heading>
        {heading}
    </Heading>
    <button on:click={toogleButton} class="text-2xl rounded-lg bg-blue-500 text-white aspect-square h-8">
        {#if collapsed}
            +
        {:else}
            -
        {/if}
    </button>
</div>
{#if !collapsed}
    <slot />
{/if}

// src/components/CollapsedMenu.tsx
import React, { useState, Children } from "react";
import TopicLink from "./TopicLink";

const CollapsedMenu = ({ heading, children }: { heading: string, children?: Children }) => {
	const [collapsed, setCollapsed] = useState(true);
	const toogleButton = () => {
		setCollapsed(!collapsed);
	};
	return(
		<div>
			<div className="flex flex-row items-center justify-between w-full p-2">
				<h1 className="text-white text-2xl" >
					{heading}
				</h1>
				<button onClick={toogleButton} className="text-4xl rounded-lg bg-blue-500 text-white aspect-square h-16">
					{collapsed ? "+" : "-"}
				</button>
			</div>
			{
				!collapsed && 
				<div>
					{children}
				</div>
			}
		</div>
	);
};

export default CollapsedMenu;
