// src/lib/Header.svelte
<script>
    import SelfCard from "./SelfCard.svelte";
    import CollapsedMenu from "./CollapsedMenu.svelte";
    import TopicLink from "./TopicLink.svelte";
    import ContentModal from "./ContentModal.svelte";
</script>
<div class="h-18 w-full bg-blue-950 flex flex-row justify-between items-center sticky top-0 flex-nowrap space-x-4 p-4" >
    <SelfCard></SelfCard>
    <ContentModal heading="Menú" >
        <CollapsedMenu heading={"The Console Logs"} >
            <TopicLink link="/blog/the-console-logs/maitei" >
                ¡Maiteĩ!
            </TopicLink>
            <TopicLink link="/blog/the-console-logs/nos-pasamos-a-svelte" >
                ¡Nos pasamos a Svelte!
            </TopicLink>
        </CollapsedMenu>
    </ContentModal>
</div>

// src/components/Header.tsx
import React from "react";
import SelfCard from "../components/SelfCard";
import ContentModal from "../components/ContentModal";
import CollapsedMenu from "../components/CollapsedMenu";
import TopicLink from "../components/TopicLink";

const Header = () => {
	return (
		<div
			className={
				"sticky top-0 flex flex-row flex-nowrap bg-blue-900" +
				" h-24 w-full items-center space-x-4 p-4 justify-between"
			}
		>
			<SelfCard />
			<ContentModal heading="Contenido">
				<CollapsedMenu heading="The Console Logs: Mi blog personal.">
					<TopicLink topic="¡Bienvenidos!" link="/" />
					<TopicLink topic="" link="/" />
				</CollapsedMenu>
			</ContentModal>
		</div>
	);
};

export default Header;
