// src/lib/TopicLink.svelte
<script lang="ts" >
    export let link:string = "";
    export let topic:string = "";
</script>
<div class="w-full text-white text-xl justify-evenly m-4">
    <a href={link} >
        <h3>
            {#if !topic}
                <slot/>
            {:else}
                {topic}
            {/if}
        </h3>
    </a>
</div>

// src/components/TopicLink.tsx
import React from "react";
import { Link } from "react-router-dom";

const TopicLink = ({ topic, link }: { topic: string, link: string }) => {
	const baseURL = "/jakkunight/#";
	return (
		<div className="w-full text-white text-xl justify-evenly m-4">
			<Link to={link} >
				<h3>
					{topic}
				</h3>
			</Link>
		</div>
	);
};

export default TopicLink;
